name: music_concept_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  image_picker: ^0.8.7
  image: ^4.0.15
  flutter_staggered_grid_view: ^0.7.0
  flutter_keyboard_visibility: ^5.4.1
  timeago: ^3.5.0
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.2
  flutter_material_design_icons: ^1.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/welcome/
    - assets/wallpapers/

  uses-material-design: true
